add_sources(GUI_SOURCES
	Button.cpp
	Checkbox.cpp
	DropDownBox.cpp
	HBox.cpp
	GUIStyle.cpp
	Label.cpp
	ListBox.cpp
	PictureButton.cpp
	PictureLabel.cpp
	ProgressBar.cpp
	RadioButton.cpp
	RadioButtonManager.cpp
	ScrollBar.cpp
	StaticContainer.cpp
	TextBox.cpp
	TextButton.cpp
	TextView.cpp
	VBox.cpp
	Widget.cpp
	WidgetWithBackground.cpp
	Window.cpp
	dune/BuilderList.cpp
	dune/ChatManager.cpp
	dune/DuneStyle.cpp
	dune/GameOptionsWindow.cpp
	dune/InGameMenu.cpp
	dune/InGameSettingsMenu.cpp
	dune/LoadSaveWindow.cpp
	dune/MessageTicker.cpp
	dune/NewsTicker.cpp
	dune/WaitingForOtherPlayers.cpp
	ObjectInterfaces/PalaceInterface.cpp
)
