add_sources(GUI_SOURCES
	Button.cpp
	Checkbox.cpp
	DropDownBox.cpp
	HBox.cpp
	GUIStyle.cpp
	Label.cpp
	ListBox.cpp
	PictureButton.cpp
	PictureLabel.cpp
	ProgressBar.cpp
	RadioButton.cpp
	RadioButtonManager.cpp
	ScrollBar.cpp
	StaticContainer.cpp
	TextBox.cpp
	TextButton.cpp
	TextView.cpp
	VBox.cpp
	Widget.cpp
	WidgetWithBackground.cpp
	Window.cpp
)

include(GUI/dune/sources.cmake)
include(GUI/ObjectInterfaces/sources.cmake)
