add_sources(GUI_SOURCES
	BuilderList.cpp
	ChatManager.cpp
	DigitsCounter.cpp
	DuneStyle.cpp
	GameOptionsWindow.cpp
	InGameMenu.cpp
	InGameSettingsMenu.cpp
	LoadSaveWindow.cpp
	MessageTicker.cpp
	NewsTicker.cpp
	WaitingForOtherPlayers.cpp
)
