message(STATUS "Configuring Clang/GCC")

set(DUNE_CLANG_FLAGS "")

set(DUNE_TARGET_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR} CACHE STRING "Target processor architecture")
set_property(CACHE DUNE_TARGET_ARCHITECTURE PROPERTY STRINGS x64 x86 arm64)

set(DUNE_TARGET_ARCHITECTURE_EXTENSION "" CACHE STRING "Specify the specific target architecture default native")
set_property(CACHE DUNE_TARGET_ARCHITECTURE_EXTENSION PROPERTY STRINGS "" default)

if(DUNE_TARGET_ARCHITECTURE_EXTENSION)
	if(DUNE_TARGET_ARCHITECTURE_EXTENSION STREQUAL "default")
	else()
		string(APPEND DUNE_CLANG_FLAGS " -march=${DUNE_TARGET_ARCHITECTURE_EXTENSION}")
	endif()
endif()

string(APPEND CMAKE_C_FLAGS ${DUNE_CLAG_FLAGS})
string(APPEND CMAKE_CXX_FLAGS ${DUNE_CLANG_FLAGS})
