add_sources(MENU_SOURCES
	AboutMenu.cpp
	BriefingMenu.cpp
	CampaignStatsMenu.cpp
	CustomGameMenu.cpp
	CustomGamePlayers.cpp
	CustomGameStatsMenu.cpp
	HouseChoiceInfoMenu.cpp
	HouseChoiceMenu.cpp
	MainMenu.cpp
	MapChoice.cpp
	MentatHelp.cpp
	MentatMenu.cpp
	MenuBase.cpp
	MultiPlayerMenu.cpp
	OptionsMenu.cpp
	SinglePlayerMenu.cpp
	SinglePlayerSkirmishMenu.cpp
)
