add_sources(CUT_SCENES_SOURCES
	CrossBlendVideoEvent.cpp
	CutScene.cpp
	CutSceneTrigger.cpp
	FadeInVideoEvent.cpp
	FadeOutVideoEvent.cpp
	Finale.cpp
	HoldPictureVideoEvent.cpp
	Intro.cpp
	Meanwhile.cpp
	Scene.cpp
	TextEvent.cpp
	VideoEvent.cpp
	WSAVideoEvent.cpp
)
