add_sources(MAP_EDITOR_SOURCES
	ChoamWindow.cpp
	LoadMapWindow.cpp
	MapEditor.cpp
	MapEditorInterface.cpp
	MapEditorOperation.cpp
	MapEditorRadarView.cpp
	MapGenerator.cpp
	MapMirror.cpp
	MapSettingsWindow.cpp
	NewMapWindow.cpp
	PlayerSettingsWindow.cpp
	ReinforcementsWindow.cpp
	TeamsWindow.cpp
)
