function(add_sources var)
    set(existing_sources ${${var}})
    set(new_sources "")
    foreach(f ${ARGN})
        file(REAL_PATH ${f} f BASE_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
        file(RELATIVE_PATH f ${CMAKE_CURRENT_SOURCE_DIR} ${f})
        list(APPEND new_sources ${f})
    endforeach()
    list(APPEND existing_sources ${new_sources})
    set(${var} ${existing_sources} PARENT_SCOPE)
endfunction()
