add_sources(MISC_SOURCES
	BlendBlitter.cpp
	draw_util.cpp
	dune_localtime.cpp
	dune_timer_resolution.cpp
	dune_wait_event.cpp
	FileSystem.cpp
	fnkdat.cpp
	IFileStream.cpp
	IMemoryStream.cpp
	InputStream.cpp
	md5.cpp
	OFileStream.cpp
	#OMemoryStream.cpp
	OutputStream.cpp
	Random.cpp
	Scaler.cpp
	SDL_LogRenderer.cpp
	sound_util.cpp
	string_util.cpp
)
