name: Coverity Scan

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  coverity:
    if: false # Disabled until upstream Coverity service reliability improves.
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Fetch repo
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Get cmake and ninja
        uses: lukka/get-cmake@v4.4.0

      - name: Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf autoconf-archive automake libtool libltdl-dev \
            gettext \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev \
            libxi-dev libxss-dev libxtst-dev libgl1-mesa-dev \
            libwayland-dev libxkbcommon-dev libegl1-mesa-dev \
            libibus-1.0-dev

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: external/vcpkg/vcpkg
          vcpkgJsonGlob: external/vcpkg/config-sdl3/vcpkg.json
          prependedCacheKey: "coverity/${{ runner.os }}"

      - name: Configure
        run: >
          cmake --preset=linux-release -B build -S .
          -DVCPKG_MANIFEST_DIR="${{ github.workspace }}/external/vcpkg/config-sdl3"

      - name: Coverity Scan
        uses: vapier/coverity-scan-action@v1
        with:
          working-directory: build
          command: cmake --build .
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
