# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: Microsoft C++ Code Analysis

on:
  push:
    branches: [modernize, master]
  pull_request:
    branches: [modernize]
  schedule:
    - cron: "41 21 * * 1"

env:
  build: "${{ github.workspace }}/build"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Get cmake and ninja
        uses: lukka/get-cmake@v4.4.0

      - name: Find MSVC (on Windows)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        shell: cmd
        run: cmake --preset=windows-analysis -B "${{ env.build }}"

      - name: Build generated sources and analysis inputs
        shell: cmd
        run: cmake --build "${{ env.build }}"

      - name: Initialize MSVC Code Analysis
        id: run-analysis
        uses: microsoft/msvc-code-analysis-action@v0.1.1
        with:
          cmakeBuildDirectory: ${{ env.build }}
          ruleset: NativeRecommendedRules.ruleset

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
