name: Ubuntu

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "apt-get"
        run: |
          #sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get dist-upgrade -y
          sudo apt-get install -y gcc-11 g++-11 gettext ninja-build

      - name: Fetch repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: gcc-11
          cxx: g++-11
          configure-options: -G Ninja -DVCPKG_TARGET_TRIPLET:STRING=x64-linux
          build-type: Release
          parallel: 8
