name: Ubuntu

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get cmake and ninja
        uses: lukka/get-cmake@latest

      - name: Fetch repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: external/vcpkg/vcpkg
          vcpkgJsonGlob: cmake/vcpkg.json
          prependedCacheKey: Ubuntu

      - name: Build
        uses: ashutoshvarma/action-cmake-build@master
        with:
          cc: gcc-11
          cxx: g++-11
          build-dir: build
          configure-options: --preset=linux-release
          build-type: Release

      - name: Block cache on failure
        if: ${{ failure() || cancelled() }}
        shell: bash
        run: echo "RUNVCPKG_NO_CACHE=1" >> $GITHUB_ENV

      - name: Test
        working-directory: build
        run: ctest
